# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-31 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='madeReservation',
            field=models.IntegerField(default=0),
        ),
    ]
