# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-31 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_db', '0002_auto_20161231_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.CharField(default='plain', max_length=40),
        ),
    ]
