# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-31 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_db', '0003_users_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=40)),
                ('foodCost', models.IntegerField(default=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
