# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-31 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_db', '0004_auto_20161231_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(default=4)),
                ('isBooked', models.BooleanField(default=False)),
            ],
        ),
    ]
