# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uth_db', '0005_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='tables',
            name='dateBooked',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tables',
            name='timeBooked',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tableId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uth_db.Tables'),
        ),
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uth_db.Order'),
        ),
    ]
