# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uth_db', '0006_auto_20161231_1605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Food',
        ),
        migrations.RenameModel(
            old_name='Tables',
            new_name='Table',
        ),
    ]
