# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uth_db', '0007_auto_20161231_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBooked', models.DateField(null=True)),
                ('timeBooked', models.TimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='tableId',
        ),
        migrations.RemoveField(
            model_name='table',
            name='dateBooked',
        ),
        migrations.RemoveField(
            model_name='table',
            name='timeBooked',
        ),
        migrations.AddField(
            model_name='table',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uth_db.Booking'),
        ),
    ]
