# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uth_db', '0008_auto_20161231_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookedBy',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='tableOrdered',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='uth_db.Table'),
        ),
    ]
