# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uth_db', '0010_booking_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrdered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='order',
        ),
        migrations.AddField(
            model_name='foodordered',
            name='foodOrdered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uth_db.Food'),
        ),
        migrations.AddField(
            model_name='foodordered',
            name='orderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uth_db.Order'),
        ),
    ]
