# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uth_db', '0011_auto_20170102_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='uth_db.Booking'),
        ),
    ]
