# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uth_db', '0013_auto_20170104_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
