# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uth_db', '0015_auto_20170111_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uth_db.Booking'),
        ),
    ]
