# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uth_db', '0016_order_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uth_db.Booking'),
        ),
    ]
